# Nome do seu fluxo de trabalho de automação
name: Monitorar Lei do Bem

# Define os gatilhos (triggers) que iniciam o fluxo
on:
  # Permite que você rode este fluxo manualmente pela aba Actions
  workflow_dispatch:

  # Gatilho de agendamento (schedule)
  schedule:
    # Roda às 12:00 UTC (9:00 no Horário de Brasília) todos os dias.
    # '0 */2 * * *' -> rodaria a cada 2 horas.
    - cron: '0 12 * * *'

# Define os "trabalhos" (jobs) que o fluxo vai executar
jobs:
  build:
    # O tipo de máquina virtual que será usada
    runs-on: ubuntu-latest

    # A sequência de passos que o trabalho executará
    steps:
      # 1. Baixa o código do seu repositório para a máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura o ambiente Python na versão especificada
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Instala as bibliotecas Python necessárias
      - name: Install dependencies
        run: pip install requests beautifulsoup4

      # 4. Executa o seu script Python
      - name: Run the monitoring script
        env:
          # Mapeia os Secrets do GitHub para variáveis de ambiente
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
        run: python alerta_lei_do_bem.py
